config/routes.rb
Ratebeer::Application.routes.draw do

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :users

  resources :sessions, only: [:new, :create]

  resources :beers

  resources :breweries

  resources :ratings, :only => [:index, :new, :create, :destroy]

  root 'breweries#index'

  get 'kaikki_bisset', to: 'beers#index'

end

app/models/rating.rb
# -*- coding: utf-8 -*-
class Rating < ActiveRecord::Base
  belongs_to :beer
  belongs_to :user   # rating kuuluu myös käyttäjään

  validates :score, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: 50,
                                    only_integer: true }

  def to_s
    "#{beer.name} #{score}"
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @ratings = Rating.all
  end

  def new
    @rating = Rating.new
    @beers = Beer.all
  end

  def create
    @rating = Rating.new params.require(:rating).permit(:score, :beer_id)

    if @rating.save
      current_user.ratings << @rating
      redirect_to user_path current_user
    else
      @beers = Beer.all
      render :new
    end
  end

  def destroy
    rating = Rating.find(params[:id])
    rating.delete
    redirect_to :back
  end
end

app/views/ratings/index.html.erb
<h2>List of ratings</h2>

<p>Number of ratings <%= @ratings.count %></p>

<ul>
  <% @ratings.each do |rating| %>
  <li> <%= rating %> 
  <%= link_to rating.user.username, rating.user  %> 
  </li>
  <% end %>
</ul>

<%= link_to 'create new rating', new_rating_path %>

app/views/ratings/new.html.erb
<h2>Create new rating</h2>

<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.select :beer_id, options_from_collection_for_select(@beers, :id, :to_s) %>
  score: <%= f.number_field :score %>
  <%= f.submit %>

<% end %>